server.port=8087
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/concesionario_db?serverTimezone=UTC&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:joseluis}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true

apify.api-token=${APIFY_API_TOKEN:apify_api_local}
apify.dataset-id=${APIFY_DATASET_ID:FxFWlaTrHD5lFuadY}
catalogo.fuente=ambos

ingesta.frecuencia=MENSUAL
ingesta.max-items=2000
apify.autoscout-dataset-id=${APIFY_AUTOSCOUT_DATASET_ID:PkP7ZzCOm4SjWNoC6}
