/*REATE TABLE IF NOT EXISTS usuarios (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS coches (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    fecha_publicacion VARCHAR(255),
    precio DOUBLE,
    descripcion VARCHAR(2000),
    marca VARCHAR(255),
    modelo VARCHAR(255),
    version VARCHAR(255),
    kilometros INT,
    anio INT,
    matriculacion VARCHAR(255),
    combustible VARCHAR(255),
    potencia_cv INT,
    cilindrada INT,
    transmision VARCHAR(255),
    tipo_carroceria VARCHAR(255),
    num_puertas INT,
    color_exterior VARCHAR(255),
    color_interior VARCHAR(255),
    estado VARCHAR(255),
    es_nacional TINYINT(1),
    revisiones_al_dia TINYINT(1),
    garantia TINYINT(1),
    imagen_url VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS coches_importados (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    apify_id VARCHAR(255),
    titulo VARCHAR(255),
    marca VARCHAR(255),
    modelo VARCHAR(255),
    kilometraje VARCHAR(255),
    combustible VARCHAR(255),
    cambio VARCHAR(255),
    matriculacion VARCHAR(255),
    precio_original DECIMAL(19,2),
    precio_con_comision DECIMAL(19,2),
    imagen_url VARCHAR(1000),
    url_original VARCHAR(500),
    fecha_ingesta DATETIME,
    activo TINYINT(1) DEFAULT 1,
    description TEXT,
    features_json TEXT,
    attributes_json TEXT,
    dealer_name VARCHAR(255),
    dealer_phone VARCHAR(255),
    dealer_whatsapp VARCHAR(255),
    dealer_score DOUBLE,
    power VARCHAR(255),
    fuel_consumption VARCHAR(255),
    co2 VARCHAR(255),
    color VARCHAR(255),
    interior_design VARCHAR(255),
    num_owners VARCHAR(255),
    hu VARCHAR(255),
    vehicle_condition VARCHAR(255),
    emission_class_val VARCHAR(255),
    num_seats VARCHAR(255),
    price_rating VARCHAR(255)
);
*/