/*import { iCoche } from "../../interfaces/iCoche";
import { mockUsersSimple } from "../mock-users";

// Datos mock de coches para pruebas
export const mockCoches: iCoche[] = [
  {
    // Datos de publicación
    id: 1,
    fechaPublicacion: '2024-10-01',
    user: mockUsersSimple[0],
    precio: 38500,
    descripcion: 'SUV premium en excelente estado. Único dueño, siempre en garaje. Mantenimiento oficial al día. Incluye pack de invierno y enganche para remolque.',
    
    // Detalles del coche
    marca: 'Audi',
    modelo: 'Q5',
    version: '2.0 TDI Quattro S-Line',
    kilometros: 45000,
    anio: 2021,
    imagenUrl: ['https://drive.google.com/thumbnail?id=1EOzk_-G3HeEMNlTfq-b2B1nqDffQrUQv&sz=w1000'],
    matriculacion: '2021-03-15',
    combustible: 'Diesel',
    potenciaCV: 190,
    cilindrada: 1968,
    transmision: 'Automática',
    tipoCarroceria: 'SUV',
    numPuertas: 5,
    colorExterior: 'Negro Phantom',
    colorInterior: 'Beige Milano',
    estado: 'Usado',
    esNacional: true,
    revisionesAlDia: true,
    garantia: true,
  },
  {
    id: 2,
    fechaPublicacion: '2024-09-15',
    user: mockUsersSimple[1],
    precio: 22900,
    descripcion: 'Híbrido eficiente y moderno con etiqueta ECO. Perfecto para ciudad y carretera. Sistema multimedia Toyota Touch 2 incluido.',
    
    marca: 'Toyota',
    modelo: 'Corolla',
    version: '1.8 Hybrid Active Tech',
    kilometros: 15000,
    anio: 2023,
    imagenUrl: ['https://placehold.co/600x400?text=Toyota+Corolla'],
    matriculacion: '2023-06-20',
    combustible: 'Híbrido',
    potenciaCV: 122,
    cilindrada: 1798,
    transmision: 'Automática',
    tipoCarroceria: 'Berlina',
    numPuertas: 5,
    colorExterior: 'Blanco Perla',
    colorInterior: 'Negro',
    estado: 'Seminuevo',
    esNacional: true,
    revisionesAlDia: true,
    garantia: true,
  },
  {
    id: 3,
    fechaPublicacion: '2024-08-20',
    user: mockUsersSimple[2],
    precio: 18000,
    descripcion: 'Deportivo compacto con gran respuesta y sonido espectacular. Llantas de 18", asientos deportivos Recaro. Para amantes de la conducción.',
    
    marca: 'Ford',
    modelo: 'Focus ST',
    version: '2.0 EcoBoost Performance',
    kilometros: 85000,
    anio: 2018,
    imagenUrl: ['https://placehold.co/600x400?text=Ford+Focus+ST'],
    matriculacion: '2018-02-10',
    combustible: 'Gasolina',
    potenciaCV: 250,
    cilindrada: 1999,
    transmision: 'Manual',
    tipoCarroceria: 'Deportivo',
    numPuertas: 5,
    colorExterior: 'Azul Performance',
    colorInterior: 'Negro/Azul',
    estado: 'Usado',
    esNacional: true,
    revisionesAlDia: true,
    garantia: false,
  },
  {
    id: 4,
    fechaPublicacion: '2024-10-05',
    user: mockUsersSimple[3],
    precio: 42000,
    descripcion: 'Eléctrico prácticamente nuevo con etiqueta CERO emisiones. Autopilot incluido, carga rápida. El futuro de la movilidad.',
    
    marca: 'Tesla',
    modelo: 'Model 3',
    version: 'Long Range RWD',
    kilometros: 5000,
    anio: 2024,
    imagenUrl: ['https://placehold.co/600x400?text=Tesla+Model+3'],
    matriculacion: '2024-04-15',
    combustible: 'Eléctrico',
    potenciaCV: 350,
    cilindrada: 0,
    transmision: 'Automática',
    tipoCarroceria: 'Berlina',
    numPuertas: 4,
    colorExterior: 'Rojo Multi-Coat',
    colorInterior: 'Blanco Premium',
    estado: 'Nuevo',
    esNacional: false,
    revisionesAlDia: true,
    garantia: true,
  },
  {
    id: 5,
    fechaPublicacion: '2024-09-30',
    user: mockUsersSimple[4],
    precio: 16500,
    descripcion: 'Compacto fiable y económico. Perfecto como primer coche o para ciudad. Muy bajo consumo y fácil aparcamiento.',
    
    marca: 'Volkswagen',
    modelo: 'Polo',
    version: '1.0 TSI Comfortline',
    kilometros: 35000,
    anio: 2020,
    imagenUrl: ['https://placehold.co/600x400?text=VW+Polo'],
    matriculacion: '2020-07-22',
    combustible: 'Gasolina',
    potenciaCV: 95,
    cilindrada: 999,
    transmision: 'Manual',
    tipoCarroceria: 'Berlina',
    numPuertas: 5,
    colorExterior: 'Gris Platino',
    colorInterior: 'Negro',
    estado: 'Usado',
    esNacional: true,
    revisionesAlDia: true,
    garantia: false,
  },
  {
    id: 6,
    fechaPublicacion: '2024-10-08',
    user: mockUsersSimple[5],
    precio: 28900,
    descripcion: 'Familiar espacioso y versátil. 7 plazas reales, maletero enorme. Ideal para familias numerosas o quienes necesitan espacio.',
    
    marca: 'Peugeot',
    modelo: '5008',
    version: '1.5 BlueHDi Allure',
    kilometros: 52000,
    anio: 2019,
    imagenUrl: ['https://placehold.co/600x400?text=Peugeot+5008'],
    matriculacion: '2019-11-08',
    combustible: 'Diesel',
    potenciaCV: 130,
    cilindrada: 1499,
    transmision: 'Manual',
    tipoCarroceria: 'Monovolumen',
    numPuertas: 5,
    colorExterior: 'Azul Magnético',
    colorInterior: 'Gris Techno',
    estado: 'Usado',
    esNacional: true,
    revisionesAlDia: true,
    garantia: false,
  },
  {
    id: 7,
    fechaPublicacion: '2024-09-25',
    user: mockUsersSimple[0],
    precio: 31200,
    descripcion: 'Berlina premium con acabados de lujo. Cuero Nappa, climatizador dual, navegador premium. Conducción suave y silenciosa.',
    
    marca: 'BMW',
    modelo: 'Serie 3',
    version: '320d Luxury Line',
    kilometros: 68000,
    anio: 2019,
    imagenUrl: ['https://placehold.co/600x400?text=BMW+Serie+3'],
    matriculacion: '2019-05-14',
    combustible: 'Diesel',
    potenciaCV: 190,
    cilindrada: 1995,
    transmision: 'Automática',
    tipoCarroceria: 'Berlina',
    numPuertas: 4,
    colorExterior: 'Blanco Alpino',
    colorInterior: 'Cuero Negro',
    estado: 'Usado',
    esNacional: true,
    revisionesAlDia: true,
    garantia: false,
  },
  {
    id: 8,
    fechaPublicacion: '2024-10-10',
    user: mockUsersSimple[2],
    precio: 19500,
    descripcion: 'SUV compacto versátil con tracción total. Perfecto para aventuras y uso diario. Muy equipado y con gran visibilidad.',
    
    marca: 'Nissan',
    modelo: 'Qashqai',
    version: '1.3 DIG-T Tekna',
    kilometros: 42000,
    anio: 2021,
    imagenUrl: [
      'https://drive.google.com/thumbnail?id=1aaPdKNJWJ1p1WvQr7SqtKMhLs77Yr0dQ&sz=w1000',
      'https://drive.google.com/thumbnail?id=1yX2rYQSg9Jc8qI-lXNFVESvjHAkpF-NK&sz=w1000'
    ],
    matriculacion: '2021-09-03',
    combustible: 'Gasolina',
    potenciaCV: 140,
    cilindrada: 1332,
    transmision: 'Manual',
    tipoCarroceria: 'SUV',
    numPuertas: 5,
    colorExterior: 'Naranja Fuego',
    colorInterior: 'Negro Alcantara',
    estado: 'Usado',
    esNacional: true,
    revisionesAlDia: true,
    garantia: true,
  }
];*/